# .streamlit/secrets.toml

# Kredensial service account Google dalam format JSON string
# Ini akan kosong di sini, karena kontennya akan diisi di Streamlit Cloud Dashboard
gcp_service_account_json = "" # Ini hanya placeholder

# Nama Spreadsheet Anda
sheet_name = "Presensi Mentoring STT NF"