[gcp_service_account]
type = "service_account"
project_id = "presensi-mentoring-stt-nf"
private_key_id = "179cc7b8562dd043272a73d7d86b080ab541bd68"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCdv9LrSCsNPCfI
TZyH6I5lW4wl49kHNdyIKQd1vR9m1jOYLCRw+GKNgsX9VUwjgL8+/Kga/fBlrCo+
yWEwSxQNpSlEbCH9Y75YMhFSSq5F/Oe4qWAL+JXWBxIyWewXSH2dDlvLHr963fvn
Exr1y3Wd/EqK8f0gPV6mHgomw6W+LRw9ztkB90ed593e+jWIoGEC6lCEzYrP7u5k
r54skUOHc6+dVS3CgCGYgNjIM2oZpqWXwhjS/dkUC8NaaOjiMxayItC37wGL2I7l
k4+2MWDGBO8QI5z3H5Crq0JhfQCA2TkeqSJvxSuGtBTJGM3V4qf6+qJ+M77Cqq0c
uicDd7AtAgMBAAECggEAAKe89go5Dmmo6O2UdMsz/e0SNJin5Z5FJ5YzeDs58PMx
0YZZadQkAKd4ncXVbVd3oZshe1YTr8K2GDWrNePIzQn+gvVQ4WXqTkVVQPFSU0aG
Jd+1qFlbexyaQ6zY8USsK8EMA494opCoMWoo+N1j+y0VBeVv2RQTm1pRTcMzj/e5
UmQTW2gSs8hRk7/hhLmNNXncwL9kyZb2/bn+kkSN9RR+sBGSWRhM1tbGQH+zrXNf
S+HDJv4okQYgyVKbnfMTYxixKPnwjAIAoZQXASys0f5WE855MApRuHBIk2dPq0/B
+SR+sNSvcglteQf44N3DPYS09ujVT04BYTlGCEqXpwKBgQDeWD8sU0oAKyGC/hl4
Mu6MTTr0Dda2QdT1v6iQZ0/hza2JkGVtgZ0OMKEiIZo3XZd9DZjlJnjXzdvizZOL
AP54OUyN2h7q9YYFTTCYxQIW7Lh9ffBoZXGOYiRWngqygLmzg4kCM5bz8pSocAvH
VI3eQwVIX0y3mGLBFEznK0h9XwKBgQC1oIkggc2fLdWrFlIUKI4W6tHf9IJAHcA3
z0soH/TLD++cnrqPdnyhWQ5QW0XNw1WXzzpMjpqDFZJUvX/pNjNt4K5AwpSvQYCf
WcYrbNE/8zcEAqsu+xG386zLJHwcYLiLizw6IGt9GKRZ+yBSfx29S7k/V9rMMOdJ
ZArM2Uax8wKBgEDf2r7iJmtaKlMANQo/Qh8pwZPIHefb2XlCzLolisdFrea/fPiw
otSrF7jPuSGCa1sPhpcF3KiK5ieM+AnM5nLJtS6GgBLqRIpzdUR95xgtRb9H6cds
Ie/7bsLfJhvjN0vLi0RbLSZMl1d2KdmlMCezwmzVcZr4GYhglfe1R1ddAoGBAI6F
6fUTRqppSijV/BSLemxrWcO219q+Pc7NoLlc0jfiSnGJcPYQ0V2/R2cxKEZ9yJW2
7JWUtZS1gb1zcoMroBHR5Is25XvdF7RzuvjqjAz1qq8/9NqJ8+54jZhfCfEuyMHf
waQPOqnQg2+Ei2mRDGI1oKkfJLdkjKnfkkYLHdmXAoGAA2AB23R7grgYkDIyO1fM
/6Bp0Bqyt7A+k59FBhuVOj5AWy3ARczhvgz1bzX1R/w3HAuIWmqf3QAtdQkdg0fs
6i7yxJvOK5/NHpbWeUugj79CYhPLUcXdOBPf3Pb5PvsunboVrt7ryCIv9/AuOoKC
PgUexBtavvmdCH7ciOTd2VE=
-----END PRIVATE KEY-----"""
client_email = "sheets-drive-monitoring@presensi-mentoring-stt-nf.iam.gserviceaccount.com"
client_id = "100171804888450116048"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/sheets-drive-monitoring%40presensi-mentoring-stt-nf.iam.gserviceaccount.com"
universe_domain = "googleapis.com"

# Nama spreadsheet Google Sheets
sheet_name = "Presensi Mentoring STT NF"
